import type {
  Lead,
  Deal,
  Client,
  Campaign,
  SeoReport,
  ContentItem,
  EmailSequence,
  Integration,
  PerformancePoint,
  CustomerSuccessSignal,
  Objection,
} from "./types";

export const leads: Lead[] = [
  {
    id: "L-1001",
    businessName: "Summit Ridge Roofing",
    ownerName: "Mark Delaney",
    website: "summitridgeroofing.com",
    phone: "+1 (720) 555-0148",
    email: "mark@summitridgeroofing.com",
    industry: "Roofing",
    location: "Denver, CO, USA",
    monthlyRevenueEstimate: 185000,
    marketingScore: 28,
    opportunityScore: 91,
    recommendedService: "Google Ads + Local SEO",
    estimatedDealValue: 3200,
    source: "Cold Outreach",
  },
  {
    id: "L-1002",
    businessName: "BrightSmile Family Dental",
    ownerName: "Dr. Priya Nair",
    website: "brightsmilefamilydental.ca",
    phone: "+1 (416) 555-0173",
    email: "priya@brightsmilefamilydental.ca",
    industry: "Dentists",
    location: "Toronto, ON, Canada",
    monthlyRevenueEstimate: 210000,
    marketingScore: 41,
    opportunityScore: 78,
    recommendedService: "Facebook Ads + Reputation Management",
    estimatedDealValue: 2800,
    source: "Referral",
  },
  {
    id: "L-1003",
    businessName: "CoolFlow HVAC Services",
    ownerName: "Tyrone Banks",
    website: "coolflowhvac.com",
    phone: "+1 (214) 555-0199",
    email: "tyrone@coolflowhvac.com",
    industry: "HVAC",
    location: "Dallas, TX, USA",
    monthlyRevenueEstimate: 320000,
    marketingScore: 19,
    opportunityScore: 95,
    recommendedService: "Google Ads + CRM Setup",
    estimatedDealValue: 4500,
    source: "SEO Audit Tool",
  },
  {
    id: "L-1004",
    businessName: "Whitfield & Cole Law Group",
    ownerName: "Elena Whitfield",
    website: "whitfieldcolelaw.com",
    phone: "+1 (312) 555-0122",
    email: "elena@whitfieldcolelaw.com",
    industry: "Law Firms",
    location: "Chicago, IL, USA",
    monthlyRevenueEstimate: 450000,
    marketingScore: 55,
    opportunityScore: 64,
    recommendedService: "SEO + Website Development",
    estimatedDealValue: 5200,
    source: "LinkedIn Outreach",
  },
  {
    id: "L-1005",
    businessName: "Glow Aesthetics Med Spa",
    ownerName: "Dr. Fatima Haddad",
    website: "glowaestheticsmedspa.com",
    phone: "+1 (480) 555-0166",
    email: "fatima@glowaestheticsmedspa.com",
    industry: "Med Spas",
    location: "Scottsdale, AZ, USA",
    monthlyRevenueEstimate: 275000,
    marketingScore: 33,
    opportunityScore: 87,
    recommendedService: "Instagram Ads + Funnel Development",
    estimatedDealValue: 3800,
    source: "Instagram DM",
  },
  {
    id: "L-1006",
    businessName: "Harborview Realty Group",
    ownerName: "Connor McBride",
    website: "harborviewrealtygroup.co.uk",
    phone: "+44 20 7946 0958",
    email: "connor@harborviewrealtygroup.co.uk",
    industry: "Real Estate",
    location: "London, UK",
    monthlyRevenueEstimate: 390000,
    marketingScore: 47,
    opportunityScore: 71,
    recommendedService: "Facebook Ads + Email Marketing",
    estimatedDealValue: 3000,
    source: "Cold Outreach",
  },
  {
    id: "L-1007",
    businessName: "Ironclad Auto Repair",
    ownerName: "Diego Ramirez",
    website: "ironcladautorepair.com",
    phone: "+1 (602) 555-0187",
    email: "diego@ironcladautorepair.com",
    industry: "Auto Repair",
    location: "Phoenix, AZ, USA",
    monthlyRevenueEstimate: 140000,
    marketingScore: 22,
    opportunityScore: 89,
    recommendedService: "Local SEO + Reputation Management",
    estimatedDealValue: 2400,
    source: "Google Maps Scan",
  },
  {
    id: "L-1008",
    businessName: "Peak Performance Gym",
    ownerName: "Jade Whitmore",
    website: "peakperformancegym.com.au",
    phone: "+61 2 8123 4567",
    email: "jade@peakperformancegym.com.au",
    industry: "Gyms",
    location: "Sydney, Australia",
    monthlyRevenueEstimate: 95000,
    marketingScore: 36,
    opportunityScore: 82,
    recommendedService: "Instagram Ads + SMS Marketing",
    estimatedDealValue: 2000,
    source: "Referral",
  },
  {
    id: "L-1009",
    businessName: "Nordic Table Restaurant",
    ownerName: "Lars Eriksson",
    website: "nordictablerestaurant.de",
    phone: "+49 30 12345678",
    email: "lars@nordictablerestaurant.de",
    industry: "Restaurants",
    location: "Berlin, Germany",
    monthlyRevenueEstimate: 120000,
    marketingScore: 44,
    opportunityScore: 68,
    recommendedService: "Social Media Management + Local SEO",
    estimatedDealValue: 1800,
    source: "Cold Outreach",
  },
  {
    id: "L-1010",
    businessName: "Cascade Construction Co.",
    ownerName: "Bill Harrington",
    website: "cascadeconstructionco.com",
    phone: "+1 (503) 555-0154",
    email: "bill@cascadeconstructionco.com",
    industry: "Construction",
    location: "Portland, OR, USA",
    monthlyRevenueEstimate: 610000,
    marketingScore: 15,
    opportunityScore: 97,
    recommendedService: "Website Development + Google Ads",
    estimatedDealValue: 6000,
    source: "SEO Audit Tool",
  },
  {
    id: "L-1011",
    businessName: "SecureLife Insurance Group",
    ownerName: "Rachel Kim",
    website: "securelifeinsurancegroup.com",
    phone: "+1 (617) 555-0134",
    email: "rachel@securelifeinsurancegroup.com",
    industry: "Insurance",
    location: "Boston, MA, USA",
    monthlyRevenueEstimate: 340000,
    marketingScore: 52,
    opportunityScore: 61,
    recommendedService: "Email Marketing + CRM Setup",
    estimatedDealValue: 2900,
    source: "Referral",
  },
  {
    id: "L-1012",
    businessName: "Wanderlust Travel Co.",
    ownerName: "Sofia Marchetti",
    website: "wanderlusttravelco.it",
    phone: "+39 06 1234 5678",
    email: "sofia@wanderlusttravelco.it",
    industry: "Travel Agencies",
    location: "Rome, Italy",
    monthlyRevenueEstimate: 165000,
    marketingScore: 39,
    opportunityScore: 75,
    recommendedService: "Facebook Ads + Branding",
    estimatedDealValue: 2200,
    source: "Instagram DM",
  },
];

export const objections: Objection[] = [
  {
    objection: "Too expensive",
    response:
      "I understand budget matters. Most clients see this as an investment, not a cost — our average client generates $4-8 back for every $1 spent within 90 days. Would it help if I showed you the ROI projection based on your industry benchmarks first?",
  },
  {
    objection: "We already have an agency",
    response:
      "That's great — it means you already believe in marketing. Most of our current clients switched to us because their previous agency wasn't providing clear reporting or results. Would you be open to a free 15-minute audit to see how your current results compare to what's possible?",
  },
  {
    objection: "No budget",
    response:
      "Totally understand. Let's flip it — what if the campaign paid for itself from the leads it generates? We can start with a smaller pilot budget scoped to your cash flow and scale once it's proven. What budget range would feel safe to test with?",
  },
  {
    objection: "Need to think about it",
    response:
      "Of course, this is an important decision. Just so I can send the most useful follow-up — is there a specific concern on your mind, like results, price, or timing? That way I'm not just following up blind.",
  },
  {
    objection: "Not interested",
    response:
      "No problem, I appreciate you being direct. Before I let you go — is that because you're happy with where leads are coming from right now, or because marketing isn't a priority at the moment? Either way is fine, just want to understand.",
  },
  {
    objection: "Send me information",
    response:
      "Happy to send that over. To make sure it's actually relevant and not generic, can I ask 2 quick questions about your current lead flow and goals first? Takes 30 seconds and means what I send actually applies to your business.",
  },
];

export const deals: Deal[] = [
  { id: "D-201", businessName: "Summit Ridge Roofing", stage: "Proposal Sent", value: 3200, owner: "Sales - Amir", lastActivity: "2 days ago" },
  { id: "D-202", businessName: "CoolFlow HVAC Services", stage: "Negotiation", value: 4500, owner: "Sales - Amir", lastActivity: "Today", objection: "Too expensive" },
  { id: "D-203", businessName: "Glow Aesthetics Med Spa", stage: "Qualified", value: 3800, owner: "Sales - Nadia", lastActivity: "1 day ago" },
  { id: "D-204", businessName: "Ironclad Auto Repair", stage: "New", value: 2400, owner: "Sales - Nadia", lastActivity: "3 hours ago" },
  { id: "D-205", businessName: "Cascade Construction Co.", stage: "Negotiation", value: 6000, owner: "Sales - Amir", lastActivity: "Today", objection: "We already have an agency" },
  { id: "D-206", businessName: "Peak Performance Gym", stage: "Won", value: 2000, owner: "Sales - Nadia", lastActivity: "5 days ago" },
  { id: "D-207", businessName: "Whitfield & Cole Law Group", stage: "Proposal Sent", value: 5200, owner: "Sales - Amir", lastActivity: "4 days ago" },
  { id: "D-208", businessName: "Harborview Realty Group", stage: "Lost", value: 3000, owner: "Sales - Nadia", lastActivity: "1 week ago", objection: "No budget" },
  { id: "D-209", businessName: "Wanderlust Travel Co.", stage: "Qualified", value: 2200, owner: "Sales - Amir", lastActivity: "2 days ago" },
  { id: "D-210", businessName: "SecureLife Insurance Group", stage: "New", value: 2900, owner: "Sales - Nadia", lastActivity: "Today" },
];

export const clients: Client[] = [
  {
    id: "C-01",
    businessName: "TrueNorth Roofing & Restoration",
    industry: "Roofing",
    plan: "Growth (Ads + SEO)",
    mrr: 3500,
    startDate: "2025-02-10",
    healthScore: 88,
    churnRisk: "Low",
    csm: "Jasmine Ortiz",
    onboarding: [
      { label: "Collect brand assets & access", done: true },
      { label: "Competitor & market research", done: true },
      { label: "Campaign build & launch", done: true },
      { label: "KPI dashboard delivered", done: true },
      { label: "30-day performance review", done: false },
    ],
  },
  {
    id: "C-02",
    businessName: "Lakeside Family Dentistry",
    industry: "Dentists",
    plan: "Starter (Local SEO)",
    mrr: 1200,
    startDate: "2025-11-02",
    healthScore: 63,
    churnRisk: "Medium",
    csm: "Jasmine Ortiz",
    onboarding: [
      { label: "Collect brand assets & access", done: true },
      { label: "Competitor & market research", done: true },
      { label: "Campaign build & launch", done: false },
      { label: "KPI dashboard delivered", done: false },
      { label: "30-day performance review", done: false },
    ],
  },
  {
    id: "C-03",
    businessName: "Apex HVAC Solutions",
    industry: "HVAC",
    plan: "Scale (Full Funnel)",
    mrr: 6200,
    startDate: "2024-08-19",
    healthScore: 94,
    churnRisk: "Low",
    csm: "Marcus Webb",
    onboarding: [
      { label: "Collect brand assets & access", done: true },
      { label: "Competitor & market research", done: true },
      { label: "Campaign build & launch", done: true },
      { label: "KPI dashboard delivered", done: true },
      { label: "30-day performance review", done: true },
    ],
  },
  {
    id: "C-04",
    businessName: "Harmon & Blake Legal",
    industry: "Law Firms",
    plan: "Growth (Ads + SEO)",
    mrr: 4100,
    startDate: "2025-06-01",
    healthScore: 41,
    churnRisk: "High",
    csm: "Marcus Webb",
    onboarding: [
      { label: "Collect brand assets & access", done: true },
      { label: "Competitor & market research", done: true },
      { label: "Campaign build & launch", done: true },
      { label: "KPI dashboard delivered", done: false },
      { label: "30-day performance review", done: false },
    ],
  },
  {
    id: "C-05",
    businessName: "Radiance Med Spa & Wellness",
    industry: "Med Spas",
    plan: "Scale (Full Funnel)",
    mrr: 5400,
    startDate: "2025-03-22",
    healthScore: 79,
    churnRisk: "Low",
    csm: "Jasmine Ortiz",
    onboarding: [
      { label: "Collect brand assets & access", done: true },
      { label: "Competitor & market research", done: true },
      { label: "Campaign build & launch", done: true },
      { label: "KPI dashboard delivered", done: true },
      { label: "30-day performance review", done: true },
    ],
  },
];

export const campaigns: Campaign[] = [
  { id: "CMP-01", client: "TrueNorth Roofing & Restoration", platform: "Google", name: "Search - Storm Damage Repair", status: "Active", budgetPerDay: 120, spend: 3180, leads: 64, cpl: 49.7, cpa: 78.3, roas: 5.8, ctr: 7.2, cpc: 3.1, conversionRate: 11.4 },
  { id: "CMP-02", client: "TrueNorth Roofing & Restoration", platform: "Facebook", name: "Lead Gen - Free Roof Inspection", status: "Active", budgetPerDay: 80, spend: 2100, leads: 52, cpl: 40.4, cpa: 65.0, roas: 4.9, ctr: 2.1, cpc: 0.85, conversionRate: 9.8 },
  { id: "CMP-03", client: "Apex HVAC Solutions", platform: "Google", name: "Search - Emergency AC Repair", status: "Active", budgetPerDay: 200, spend: 5860, leads: 118, cpl: 49.7, cpa: 71.2, roas: 6.4, ctr: 8.9, cpc: 2.4, conversionRate: 13.1 },
  { id: "CMP-04", client: "Apex HVAC Solutions", platform: "Google", name: "PMax - Full Service HVAC", status: "Learning", budgetPerDay: 150, spend: 1980, leads: 31, cpl: 63.9, cpa: 92.1, roas: 3.8, ctr: 4.5, cpc: 1.9, conversionRate: 8.2 },
  { id: "CMP-05", client: "Radiance Med Spa & Wellness", platform: "Facebook", name: "Instagram - Botox Promo", status: "Active", budgetPerDay: 100, spend: 2790, leads: 87, cpl: 32.1, cpa: 54.6, roas: 7.1, ctr: 3.4, cpc: 0.62, conversionRate: 14.8 },
  { id: "CMP-06", client: "Radiance Med Spa & Wellness", platform: "Facebook", name: "Retargeting - Consult Booking", status: "Active", budgetPerDay: 45, spend: 1215, leads: 39, cpl: 31.2, cpa: 48.9, roas: 8.3, ctr: 5.1, cpc: 0.71, conversionRate: 17.2 },
  { id: "CMP-07", client: "Harmon & Blake Legal", platform: "Google", name: "Search - Personal Injury Leads", status: "Paused", budgetPerDay: 180, spend: 4320, leads: 22, cpl: 196.4, cpa: 285.0, roas: 2.1, ctr: 3.8, cpc: 8.9, conversionRate: 4.1 },
  { id: "CMP-08", client: "Lakeside Family Dentistry", platform: "Google", name: "Search - New Patient Offer", status: "Active", budgetPerDay: 60, spend: 890, leads: 21, cpl: 42.4, cpa: 68.0, roas: 4.2, ctr: 6.7, cpc: 2.1, conversionRate: 10.5 },
];

export const seoReports: SeoReport[] = [
  { id: "SEO-01", client: "TrueNorth Roofing & Restoration", industry: "Roofing", keywordsTracked: 85, keywordsTop10: 34, organicTraffic: 4200, trafficChangePct: 22, domainAuthority: 31, backlinksGained: 18, localPackRankings: 7 },
  { id: "SEO-02", client: "Lakeside Family Dentistry", industry: "Dentists", keywordsTracked: 60, keywordsTop10: 12, organicTraffic: 1850, trafficChangePct: 8, domainAuthority: 22, backlinksGained: 6, localPackRankings: 3 },
  { id: "SEO-03", client: "Apex HVAC Solutions", industry: "HVAC", keywordsTracked: 110, keywordsTop10: 58, organicTraffic: 7600, trafficChangePct: 34, domainAuthority: 42, backlinksGained: 27, localPackRankings: 9 },
  { id: "SEO-04", client: "Harmon & Blake Legal", industry: "Law Firms", keywordsTracked: 95, keywordsTop10: 19, organicTraffic: 2900, trafficChangePct: -4, domainAuthority: 28, backlinksGained: 4, localPackRankings: 2 },
  { id: "SEO-05", client: "Radiance Med Spa & Wellness", industry: "Med Spas", keywordsTracked: 70, keywordsTop10: 41, organicTraffic: 5100, trafficChangePct: 29, domainAuthority: 35, backlinksGained: 21, localPackRankings: 8 },
];

export const contentCalendar: ContentItem[] = [
  { day: 1, type: "Reel", topic: "Before/after transformation", status: "Published" },
  { day: 3, type: "Carousel", topic: "5 signs you need this service", status: "Published" },
  { day: 5, type: "Story", topic: "Behind-the-scenes team intro", status: "Published" },
  { day: 7, type: "Static Post", topic: "Client testimonial spotlight", status: "Scheduled" },
  { day: 9, type: "Reel", topic: "Common myth debunked", status: "Scheduled" },
  { day: 12, type: "Carousel", topic: "Pricing & packages explained", status: "In Production" },
  { day: 15, type: "Reel", topic: "Day in the life at the business", status: "In Production" },
  { day: 18, type: "Story", topic: "Limited-time promo countdown", status: "Planned" },
  { day: 21, type: "Static Post", topic: "Educational tip #1", status: "Planned" },
  { day: 24, type: "Carousel", topic: "Case study breakdown", status: "Planned" },
  { day: 27, type: "Reel", topic: "Trending audio + service tie-in", status: "Planned" },
  { day: 30, type: "Static Post", topic: "Month recap + review request", status: "Planned" },
];

export const emailSequences: EmailSequence[] = [
  { id: "EM-1", name: "New Client Welcome Series", type: "Welcome", emails: 5, openRate: 61, clickRate: 18, active: true },
  { id: "EM-2", name: "Lead Follow-Up (Day 1-14)", type: "Follow-Up", emails: 7, openRate: 48, clickRate: 12, active: true },
  { id: "EM-3", name: "Monthly Value Nurture", type: "Nurture", emails: 4, openRate: 39, clickRate: 9, active: true },
  { id: "EM-4", name: "Dormant Lead Win-Back", type: "Re-Engagement", emails: 3, openRate: 24, clickRate: 5, active: true },
  { id: "EM-5", name: "Seasonal Promo Blast", type: "Promotional", emails: 2, openRate: 33, clickRate: 7, active: false },
];

export const integrations: Integration[] = [
  { name: "GoHighLevel", category: "CRM", status: "Connected", syncing: "Leads, pipelines, appointments" },
  { name: "HubSpot", category: "CRM", status: "Not Connected", syncing: "—" },
  { name: "Twilio", category: "SMS", status: "Connected", syncing: "Appointment reminders, follow-ups" },
  { name: "Stripe", category: "Billing", status: "Connected", syncing: "Client invoicing, MRR tracking" },
  { name: "Google Calendar", category: "Scheduling", status: "Connected", syncing: "Sales & CS meetings" },
  { name: "Slack", category: "Notifications", status: "Connected", syncing: "New lead & churn-risk alerts" },
  { name: "Zapier", category: "Automation", status: "Connected", syncing: "Cross-tool workflow triggers" },
  { name: "Gmail", category: "Email", status: "Connected", syncing: "Outreach & nurture sequences" },
  { name: "Make", category: "Automation", status: "Not Connected", syncing: "—" },
  { name: "Salesforce", category: "CRM", status: "Not Connected", syncing: "—" },
];

export const performanceHistory: PerformancePoint[] = [
  { label: "Feb", revenue: 142000, profit: 51000, leads: 410 },
  { label: "Mar", revenue: 158000, profit: 58000, leads: 452 },
  { label: "Apr", revenue: 151000, profit: 54000, leads: 431 },
  { label: "May", revenue: 173000, profit: 66000, leads: 498 },
  { label: "Jun", revenue: 189000, profit: 74000, leads: 540 },
  { label: "Jul", revenue: 204000, profit: 83000, leads: 587 },
];

export const customerSuccessSignals: CustomerSuccessSignal[] = [
  { client: "TrueNorth Roofing & Restoration", satisfaction: 92, churnRisk: "Low", lastCheckIn: "3 days ago", upsellOpportunity: "Add Local SEO retainer", note: "Consistently hitting lead targets; asked about expanding to 2nd service area." },
  { client: "Lakeside Family Dentistry", satisfaction: 68, churnRisk: "Medium", lastCheckIn: "9 days ago", upsellOpportunity: null, note: "Slower ramp on new-patient volume; needs a check-in call this week." },
  { client: "Apex HVAC Solutions", satisfaction: 96, churnRisk: "Low", lastCheckIn: "1 day ago", upsellOpportunity: "Upgrade to Scale plan + AI voice agent", note: "Best performing account this quarter; strong upsell candidate." },
  { client: "Harmon & Blake Legal", satisfaction: 38, churnRisk: "High", lastCheckIn: "16 days ago", upsellOpportunity: null, note: "Paused campaign due to cost-per-lead concerns; escalate to account manager immediately." },
  { client: "Radiance Med Spa & Wellness", satisfaction: 89, churnRisk: "Low", lastCheckIn: "4 days ago", upsellOpportunity: "Cross-sell email marketing retainer", note: "Great ROAS; open to expanding into email + SMS." },
];

export const kpis = {
  mrr: clients.reduce((sum, c) => sum + c.mrr, 0),
  activeClients: clients.length,
  pipelineValue: deals
    .filter((d) => d.stage !== "Won" && d.stage !== "Lost")
    .reduce((sum, d) => sum + d.value, 0),
  wonThisMonth: deals.filter((d) => d.stage === "Won").reduce((sum, d) => sum + d.value, 0),
  avgHealthScore: Math.round(
    clients.reduce((sum, c) => sum + c.healthScore, 0) / clients.length
  ),
  totalLeadsThisMonth: campaigns.reduce((sum, c) => sum + c.leads, 0) + leads.length,
  blendedRoas:
    Math.round(
      (campaigns.reduce((sum, c) => sum + c.roas * c.spend, 0) /
        campaigns.reduce((sum, c) => sum + c.spend, 0)) *
        10
    ) / 10,
  churnRiskClients: clients.filter((c) => c.churnRisk === "High").length,
};
